 Open file error in file :                                                      
                                                                                
                                                                                
                        
 C:\BackUp-December23-2011\Backup November 2011\Algorithms\Own Algorithms\DREAM\
 Sequential\example_7\H1D\Selector.in                                           
                                                                                
                        
